import Head from "next/head";
import { api } from "~/utils/api";
import { ActionIcon, AppShell, Button, Group, Header, Navbar, useMantineColorScheme } from "@mantine/core";
import { IconSun, IconMoonStars } from '@tabler/icons-react';

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <AppShell
            padding="md"
            navbar={
              <Navbar width={{ base: 300 }} height='100%' p="xs">
                {/* Navbar content */}This is my apparent Navabr
              </Navbar>
            }
            header={<Header height={60} p="xs">
              <Group sx={{ height: '100%' }} px={20} position="apart">
           My Logo
            <ActionIcon variant="default" onClick={() => toggleColorScheme()} size={30}>
              {colorScheme === 'dark' ? <IconSun size="1rem" /> : <IconMoonStars size="1rem" />}
            </ActionIcon>
          </Group>
            </Header>}
            styles={(theme) => ({
              main: {
                backgroundColor:
                  theme.colorScheme === "dark"
                    ? theme.colors.dark[8]
                    : theme.colors.gray[0],
              },
            })}
          >
            <h1>Testing The Application</h1>
          </AppShell>
        </div>
      </main>
    </>
  );
}
